# Generated by Django 5.0.6 on 2024-06-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Changeset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the changeset title', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter the changeset description (optional)', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Changeset',
                'verbose_name_plural': 'Changesets',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the project title', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter the project description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(help_text='Enter the file name', max_length=200, verbose_name='File')),
                ('symbol', models.CharField(help_text='Enter the symbol name', max_length=200, verbose_name='Symbol')),
                ('textfield', models.TextField(help_text='Enter the context text', verbose_name='TextField')),
                ('changeset', models.ForeignKey(help_text='Select the changeset', on_delete=django.db.models.deletion.CASCADE, to='context.changeset', verbose_name='Changeset')),
            ],
            options={
                'verbose_name': 'Context',
                'verbose_name_plural': 'Contexts',
            },
        ),
        migrations.AddField(
            model_name='changeset',
            name='project',
            field=models.ForeignKey(help_text='Select the project', on_delete=django.db.models.deletion.CASCADE, to='context.project', verbose_name='Project'),
        ),
    ]
