# Generated by Django 5.0.6 on 2024-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='textfield',
        ),
    ]
