# Generated by Django 5.0.6 on 2024-06-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_remove_context_textfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='context',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='context',
            unique_together={('change_set', 'file', 'symbol')},
        ),
    ]
