#!/bin/bash

# Function to list files
list_files() {
    find . -type f -not -path '*/\.git/*' $(sed 's/^/-not -path "*/' .exclude | sed 's/$$/*"/' | tr '\n' ' ')
}

# Get the list of files
files=$(list_files)

# Run aider with the list of files
aider $files
