#!/bin/bash

# Function to list files
list_files() {
    find . -type f \
    -not -path '*/\.git/*' \
    -not -path '*.pyc' \
    -not -path '*__pycache__*' \
    -not -path '*db.sqlite3' \
    -not -path '*LICENSE' \
    -not -path '*migrations*' \
    -not -path '*asgi.py' \
    -not -path '*wsgi.py' \
    -not -path '*manage.py' \
    -not -path '*~' \
    -not -path '*Makefile' \
    -not -path '*.aider*' \
    -not -path '*changeset.py' \
    -not -path '*changeset.md' \
    -not -path '*.gitignore'
}

# Get the list of files
files=$(list_files)

# Run aider with the list of files
aider $files
